name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      job_to_run:
        description: 'Job to run'     
        required: true
        default: 'changes' 
        type: choice
        options:
        - changes
        - squid_proxy
jobs:

  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      squid-proxy: ${{ steps.filter.outputs.squid-proxy }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          squid-proxy:
            - 'squid-proxy/**'
          
  build:
    needs: changes
    if: ${{ needs.changes.outputs.squid-proxy == 'true' || inputs.job_to_run == 'squid_proxy' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: squid-proxy
